# -*- coding: utf-8 -*-
"""Python_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dEpbrr4DqvtKb7jMRQ5lXzv3V5DIQKOM
"""

str = 'Shreyas is very good'

"""**Task -1: Some of the other build in function of String**"""

new = str.title()
print(new)

new1 = str.split()
print(new1)

new2 = str.center(200)
print(new2)

"""Task-2: Check if 'to' is present in 'Welcome to Python'"""

String = 'Welcome to Python'
'to' in String

"""**Task -3: Go through inbuild methods like remove(), count(), clear(), sort(), reverse() in lists**"""

animals = ['dog', 'rabbit','lion','cat']
animals.remove('dog')
print(animals)

animals = ['dog', 'rabbit','lion','cat','cat']
count = animals.count('cat')
print(count)

animals = ['dog', 'rabbit','lion','cat','cat']

animals

animals.clear()
animals

list = [3,7,1,9,2,3,3,7,22,44,12,17]
list.sort()
print(list)

list.reverse()
list

"""**Task-4: Add and Remove elements from a tuple**"""

tuple = ('s','h','r','e','y','a','s')
tuple = tuple + ('is',)
print(tuple)

tuple = tuple[:3] + tuple[5:]
tuple

"""**Task -5: Go through diffrence() and symmetric diffrence()**"""

A= {1, 2, 3, 4, 5} 
B= {6, 7, 3, 9, 4} 
print(A.symmetric_difference(B))

print(A.difference(B))

"""***Task-6: Ask 2 nos. from users and store in num1 & num2 and do Various operation ***"""

def add(num1, num2): 
	return num1 + num2 

def subtract(num1, num2): 
	return num1 - num2 

def multiply(num1, num2): 
	return num1 * num2 

def divide(num1, num2): 
	return num1 / num2 
 
number_1 = int(input("Enter first number: ")) 
number_2 = int(input("Enter second number: ")) 

print("Please select operation -\n"
		"1. Add\n" 
		"2. Subtract\n"
		"3. Multiply\n" 
		"4. Divide\n")

select = input("Select operations form 1, 2, 3, 4 :")

if select == '1': 
	print(number_1, "+", number_2, "=", 
					add(number_1, number_2)) 

elif select == '2': 
	print(number_1, "-", number_2, "=", 
					subtract(number_1, number_2)) 

elif select == '3': 
	print(number_1, "*", number_2, "=", 
					multiply(number_1, number_2)) 

elif select == '4': 
	print(number_1, "/", number_2, "=", 
					divide(number_1, number_2)) 
else: 
	print("Invalid input")

"""**Task -7: Use recursion to print numbers from 1 to 10 without loops**"""

def printNumbers(n): 
    if n > 0: 
        printNumbers(n - 1) 
        print(n)

printNumbers(10)

"""**Task -8: Iterate over tuple, sets and Dictionary**"""

tupleIterate = (10,20,30,40,50)
for i in tupleIterate:
  print(i)

setIterate = set("Shreyas")
for i in setIterate:
  print(i)

dataScience = {
    1:'Python',2:'Maths',3:'ML',4:'NLP'
}

for i,j in dataScience.items():
  print(i,j)

"""**Task 9: Go through reduce(), zip() and enumaerate() functions**"""

import functools

num =[25,1,69,3,4,5]
print (functools.reduce(lambda a,b : a+b,num))

print (functools.reduce(lambda a,b : a if a > b else b,num))

name = [ "Shreyas", "Jay", "Vinay" ] 
roll_no = [ 4, 1, 3 ] 
marks = [ 40, 50, 60 ]
hi = zip(name,roll_no, marks)
hi = set(hi)
print(hi)

"""**Task-10: How to read excel sheet using pandas?**"""

import pandas as pd
df = pd.read_excel ('Path where the Excel file is stored')
print (df)